cc_library(
  name="support",
  hdrs=glob(["include/mf/support/*.hpp"]),
  strip_include_prefix="include",
  visibility=["//visibility:public"],
)

cc_library(
  name="mf",
  hdrs=[
    "include/mf/multi_field_array.hpp",
    "include/mf/multi_field_array_fwd.hpp",
    "include/mf/zip_iterator.hpp"
  ],
  strip_include_prefix="include",
  visibility=["//visibility:public"],
  deps=[
    ":support"
  ]
)
